[tool.poetry]
name = "genai-blueprint"
version = "0.1.2"
description = ""
authors = ["Thierry Caminel <thierry.caminel@eviden.com>"]
readme = "README.md"

[tool.poetry.urls]
Homepage = "https://github.com/tcaminel-pro/genai-blueprint"
Repository = "https://github.com/tcaminel-pro/genai-blueprint"


[tool.poetry.dependencies]
python = ">=3.10,<=3.12"
pydantic = "^2.7.0"
langchain = "^0.3.7"
langchain-core = "^0.3.15"
langchain-community = "^0.3.5"
langchain-experimental = "^0.3.3"
langgraph = "^0.2.45"
langserve = "^0.3.0"
langchainhub = "^0.1.21"
langchain-groq = "^0.2.1"
langchain-openai = "^0.2.6"
langchain-chroma = "^0.1.0"
devtools = "^0.12.2"
chromadb = "^0.5.17"
fastapi = "^0.110.1"
uvicorn = "^0.27.1"
httpx = "^0.27.0"
typer = "^0.9.0"
streamlit = "^1.32.1"
grandalf = "^0.8"
sse-starlette = "^2.1.0"
tabulate = "^0.9.0"
tiktoken = "^0.7.0"
# giskard = "^2.15.1"
pypdf = "^4.2.0"
openpyxl = "^3.1.4"
python-dotenv = "^1.0.1"
# pygraphviz = "^1.13"
json-repair = "^0.30.0"
langchain-huggingface = "^0.1.2"
langchain-ollama = "^0.2.0"
chroma = "^0.2.0"





[tool.poetry.group.crewai]  # Install : poetry install --with crewai 
optional = true

[tool.poetry.group.crewai.dependencies]
#crewai-tools = "^0.4.8"


[tool.poetry.group.transformers]  # Install : poetry install --with transformers 
# Warning : reguire 5 GB at least + storage for models 
optional = true

[tool.poetry.group.transformers.dependencies]
langchain-huggingface = "^0.1.2"
sentence-transformers = "^2.6.1"
accelerate = "^0.30.1"

[tool.poetry.group.demos]  # Install : poetry install --with demos 
optional = true

[tool.poetry.group.demos.dependencies]
bs4 = "^0.0.2"
lark = "^1.1.9"
tavily-python = "^0.3.3"
plotly = "^5.22.0"
yfinance = "^0.2.38"
rank-bm25 = "^0.2.2"
spacy = "^3.7.4"
matplotlib = "^3.9.0"
sqlalchemy = "^2.0.29"
unidecode = "^1.3.8"
abbreviations = "^0.2.5"
enchant = "^0.0.1"
duckduckgo-search = "^6.1.6"


[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
ipykernel = "^6.29.4"
ruff = "^0.1.4"
ipywidgets = "^8.1.2"
#diagrams = "^0.23.4"

[tool.ruff]
select = [ "E", "F", "I" ]
ignore = [ "E501" ]
builtins = ["ic", "debug"]

[tool.pyright]
pythonVersion = "3.10"
pythonPlatform = "Linux"
reportTypedDictNotRequiredAccess = false  # Avoid warnings in LangGraph

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

